/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xiaogenliu' at '16-7-12 下午7:45' with Gradle 1.11
 *
 * @author xiaogenliu, @date 16-7-12 下午7:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
